web:
  build: .
  ports:
    - '3000:3000'
  links:
    - db:db
    - redis:redis
  volumes:
    - .:/app
    - bundle:/usr/local/bundle
  command: /bin/bash -c "bundle install && bundle exec puma"
db:
  restart: always
  image: postgres:12
  volumes:
    - .:/app
  environment:
    POSTGRES_USER: app_user
    POSTGRES_PASSWORD: app_password
redis:
  image: redis:5
